# -*- coding: utf-8 -*-
"""guesser-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rexD6a8wL5HU9U_lrkSnVslXgSlcAgHB
"""

import streamlit as st
import random
import time

# List of countries
countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
    "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas",
    "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
    "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
    "Bulgaria", "Burkina Faso", "Burundi", "Cape Verde", "Cambodia", "Cameroon",
    "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba",
    "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada",
    "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
    "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
    "Kiribati", "North Korea", "South Korea", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
    "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
    "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
    "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe",
    "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
    "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan",
    "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
    "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
    "Vietnam", "Yemen", "Zambia", "Zimbabwe"
]

obscure_countries = [
    "Bhutan", "Comoros", "Djibouti", "Eswatini", "Kiribati", "Marshall Islands",
    "Micronesia", "Nauru", "Palau", "Sao Tome and Principe", "Solomon Islands",
    "Tajikistan", "Timor-Leste", "Tuvalu", "Vanuatu", "Yemen"
]

# Set Page Config
st.set_page_config(page_title="Country Guesser", page_icon="🌍", layout="centered")

st.title("🌍 Country Guesser")
st.markdown("""
A mystery country will be chosen and it will be spelled letter by letter in real-time.
The aim is to guess the country before it is fully spelled!
*Please use capital letters at the start of each word.*
""")

# Initialize Session State
if "round_num" not in st.state:
    st.session_state.round_num = 1
if "used_countries" not in st.session_state:
    st.session_state.used_countries = []
if "current_country" not in st.session_state:
    st.session_state.current_country = None
if "revealed_count" not in st.session_state:
    st.session_state.revealed_count = 1
if "game_over" not in st.session_state:
    st.session_state.game_over = False
if "last_reveal_time" not in st.session_state:
    st.session_state.last_reveal_time = time.time()
if "game_started" not in st.session_state:
    st.session_state.game_started = False
if "feedback" not in st.session_state:
    st.session_state.feedback = ""

# Sidebar - Difficulty Selection
st.sidebar.header("⚙️ Game Settings")
difficulty = st.sidebar.selectbox(
    "Select Difficulty:",
    ["Easy (3.0 seconds)", "Medium (1.5 seconds)", "Hard (0.75 seconds)"]
)

speed_map = {
    "Easy (3.0 seconds)": 3.0,
    "Medium (1.5 seconds)": 1.5,
    "Hard (0.75 seconds)": 0.75
}
reveal_delay = speed_map[difficulty]

# Function to pick new country according to round logic
def pick_country():
    if st.session_state.round_num >= 5:
        available = [c for c in obscure_countries if c not in st.session_state.used_countries]
        if not available:
            available = obscure_countries
    else:
        available = [c for c in countries if c not in st.session_state.used_countries]
        if not available:
            available = countries

    chosen = random.choice(available)
    st.session_state.used_countries.append(chosen)
    st.session_state.current_country = chosen
    st.session_state.revealed_count = 1
    st.session_state.last_reveal_time = time.time()
    st.session_state.game_over = False
    st.session_state.feedback = ""

# Start/Restart Button
if not st.session_state.game_started:
    if st.button("🚀 Start Game", type="primary"):
        st.session_state.game_started = True
        st.session_state.round_num = 1
        st.session_state.used_countries = []
        pick_country()
        st.rerun()

if st.session_state.game_started:
    # Header Info
    col1, col2 = st.columns(2)
    with col1:
        st.subheader(f"🚩 Round: {st.session_state.round_num}")
    with col2:
        if st.session_state.round_num >= 5:
            st.info("🔥 Expert Mode: Obscure Countries!")

    country = st.session_state.current_country

    # Real-time letter timer check
    now = time.time()
    if not st.session_state.game_over and st.session_state.revealed_count < len(country):
        if now - st.session_state.last_reveal_time >= reveal_delay:
            st.session_state.revealed_count += 1
            st.session_state.last_reveal_time = now

    # Format revealed word display
    revealed_text = ""
    for i in range(len(country)):
        if i < st.session_state.revealed_count:
            revealed_text += country[i] + " "
        else:
            if country[i] == ' ':
                revealed_text += "   "
            else:
                revealed_text += "_ "

    # Live UI Box for the word
    st.markdown("### Mystery Country:")
    st.code(revealed_text, language="text")

    # Feedback display
    if st.session_state.feedback:
        st.warning(st.session_state.feedback)

    # Check if fully revealed without guessing
    if st.session_state.revealed_count >= len(country) and not st.session_state.game_over:
        st.session_state.game_over = True
        st.error(f"❌ Time's up! You didn't guess correctly. The country was: **{country}**")
        st.write(f"🎉 You made it all the way to **ROUND {st.session_state.round_num}**. Good job!")

    # Guess Submission Form
    if not st.session_state.game_over:
        with st.form(key="guess_form", clear_on_submit=True):
            user_guess = st.text_input("Guess the country being spelled:", key="guess_input")
            submit = st.form_submit_button("Submit Guess")

            if submit and user_guess:
                if user_guess.isdigit():
                    st.session_state.feedback = "I'm sorry, but that's not a word."
                elif user_guess.strip().lower() == country.lower():
                    st.success(f"🎉 Congratulations, you guessed the country: **{country}**!")
                    st.session_state.round_num += 1
                    time.sleep(1.5)
                    pick_country()
                    st.rerun()
                else:
                    st.session_state.feedback = "Wrong guess! Here's another letter. Keep trying!"
                    st.rerun()

    # Next Round / Restart Button on Game Over
    if st.session_state.game_over:
        if st.button("🔄 Restart Game", type="primary"):
            st.session_state.round_num = 1
            st.session_state.used_countries = []
            pick_country()
            st.rerun()

    # Auto-refresh loop to keep real-time countdown active
    if not st.session_state.game_over and st.session_state.revealed_count < len(country):
        time.sleep(0.1)
        st.rerun()